version: '3'
services:
  frontend:
    build:
      context: ./packages/frontend/
      dockerfile: Dockerfile
    ports:
      - '3000:80'
  backend:
    build:
      context: ./packages/backend/
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
